esphome:
  name: esphome-web-123456
  friendly_name: bedroom-lock

esp8266:
  board: d1_mini
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom_doorlock_project_api_key

ota:
  platform: esphome
  password: !secret bedroom_doorlock_project_ota_password

web_server:
  port: 80
  version: 2
  include_internal: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esphome-web-123456"
    password: !secret bedroom_doorlock_project_fallback_ap_password

captive_portal:


# Start board config
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D7
    frequency: 50Hz

servo:
  - id: lock_servo
    output: pwm_output
    restore: true
    transition_length: 2s
    auto_detach_time: 2s


lock:
  - platform: template
    id: lock_template
    name: "Lock Template"
    icon: "mdi:lock"
    optimistic: true
    lock_action:
      - servo.write:
          id: lock_servo
          level: !lambda return id(locked_servo_position).state;
    unlock_action:
      - servo.write:
          id: lock_servo
          level: !lambda return id(unlocked_servo_position).state;

binary_sensor:
  - platform: gpio
    name: "Switch"
    id: push_button
    on_press:
      then:
        lambda: |-
          if (id(lock_template).state == LOCK_STATE_LOCKED ) {
            id(lock_template).unlock();
          } else {
            id(lock_template).lock();
          }
    pin:
      number: D1
      inverted: true
      mode:
        input: true
        pullup: true


number:
  - platform: template
    name: Locked servo position
    id: locked_servo_position
    entity_category: config
    min_value: -1
    max_value: 1
    initial_value: -0.7
    optimistic: true
    step: 0.1
    restore_value: true
    mode: slider
  - platform: template
    name: Unlocked servo position
    id: unlocked_servo_position
    entity_category: config
    min_value: -1
    max_value: 1
    initial_value: 0.8
    optimistic: true
    step: 0.1
    restore_value: true
    mode: slider
  - platform: template
    name: Transition Length (sec)
    id: servo_transition_length
    entity_category: config
    min_value: 0
    max_value: 5
    initial_value: 2
    optimistic: true
    step: 0.1
    restore_value: true
    mode: box
    set_action:
      lambda: |-
        return id(lock_servo).set_transition_length(x * 1000);
  - platform: template
    name: Auto Detach Time (sec)
    id: servo_auto_detach_time
    entity_category: config
    min_value: 0
    max_value: 5
    initial_value: 2
    optimistic: true
    step: 0.1
    restore_value: true
    mode: box
    set_action:
      lambda: |-
        return id(lock_servo).set_auto_detach_time(x * 1000);
